### ISSUE TITLE
Create a game

### ISSUE THREAD

**Issue by sachin-poolamannil** [STEP-tw/acquire-legends#1]
As a _player_

I want to _create a game._

So that
 - _I may start game._
 - _others can join._

**Additional Details**

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I want to create game, I land on homepage._
  - When _game is not created already._
  - Then _a create game option should be available._

- [x] Criteria 2
  - Given _I want to create game._
  - When _I click on **create game** button._
  - Then _create game pop-up should appear._

- [x] Criteria 3
  - Given _I want to create game, I am on home page._
  - When _I enter my name, number of players and click on **create** button._
  - Then _game should be created and waiting message should be displayed._

**Comment by HarVar-B** [comment]
Given: I want to create game.
When: I click on create game button.
Then: create game pop-up should appear.

==> I don't expect "Create game" & "Join game" buttons to be visible.

**Comment by HarVar-B** [comment]
![screen shot 2018-02-16 at 11 10 55 am](https://user-images.githubusercontent.com/34670602/36294971-58f56c5c-130a-11e8-9188-07557e17ec22.png)

App shouldn't respond to invalid player-count.

**Comment by HarVar-B** [comment]
Given : There is no existing game.
When : I land on homePage.
Then : I don't expect "Join game" button to be visible.
