### ISSUE TITLE
When player playing tiles of any 2 games should be different from each other.

### ISSUE THREAD

**Issue by yogiraj99** [STEP-tw/acquire-legends#117]
As a _role_

I want to _get different tiles for 2 different games_

So that I may _play without using tiles of other game_

**Additional Details**
There is game running other than I am playing.
**Acceptance Criteria**

- [ ] Criteria 1
  - Given _I am playing a game_
  - When _start game_
  - Then _my game tiles should be different from other game_
- [ ] Criteria 2
  - Given _I ended a old game._
  - When _I start new game_
  - Then _I should get different tiles and not from tiles remaining of older game.

As shown in following image I am got only 5 tiles which are remaining tiles of older game.

![screenshot 2018-03-12 16 05 23](https://user-images.githubusercontent.com/34642513/37280159-fb67c852-2612-11e8-901f-700af271c1ca.png)

**Comment by sree96** [comment]
Could you please add reproduction steps??
