### ISSUE TITLE
Player can choose to sell and/or keep shares of merging hotel.

### ISSUE THREAD

**Issue by sree96** [STEP-tw/acquire-legends#22]
As a _player_

I want to _sell and/or keep shares of merging hotel._

So that I may _encash the shares and/or keep it._

**Additional Details**
Game is running.
Merge has happened.
It is my turn of post merger action.

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I have shares to sell._
  - When _I choose the number of shares to sell and click on done._
  - Then _the chosen number of shares will be encashed, rest shares will be kept._

- [x] Criteria 2
  - Given _I have shares to sell._
  - When _I choose the number of shares to sell and click on done._
  - Then _the chosen number of shares will be deducted from my shares._

- [x] Criteria 3
  - Given _I have shares to sell._
  - When _I choose the number of shares to sell and click on done._
  - Then _the chosen number of shares will added to the available shares of that hotel._

**Comment by mrveera** [comment]
UI should improve
