### ISSUE TITLE
Merging of more than 2 hotels

### ISSUE THREAD

**Issue by sree96** [STEP-tw/acquire-legends#27]
As a _Player_

I want to _merge more than 2 unequal sized hotels_

So that I may _get advantage of that_

**Additional Details**
*I have already joined game.
*There are more than 2 hotels running.

**Acceptance Criteria**

- [x] Criteria 1
  - Given _it is my turn to place tile._
  - When _I place a tile adjacent to more than two different sized hotels._
  - Then _largest hotel survives._

- [x] Criteria 2
  - Given _it is my turn to place tile._
  - When _I place a tile adjacent to more than two different sized hotels._
  - Then _smaller hotels are merged one at a time starting form second largest._

- [x] Criteria 3
  - Given _it is my turn to place tile._
  - When _I place a tile adjacent to more than two different sized hotels._
  - Then _merging process of hotels should be same as normal merging of 2 unequal sized hotels but one at a time._

**Comment by mrveera** [comment]
It seems like I need to refresh page to update merged hotels on screen

**Comment by mrveera** [comment]
![screen shot 2018-02-26 at 11 48 17 am](https://user-images.githubusercontent.com/17177346/36655847-2ebfe6ae-1aeb-11e8-886e-24efbfbfbbb1.png)

You can refer above image
