### ISSUE TITLE
Join game

### ISSUE THREAD

**Issue by sachin-poolamannil** [STEP-tw/acquire-legends#3]
As a _player_

I want to _join a game._

So that I may _play._

**Additional Details**
Game is already created.

**Acceptance Criteria**
- [x] Criteria 1
  - Given _game is already created._
  - When _I land on homepage._
  - Then _join-game page should appear._

- [x] Criteria 2
  - Given _I'm on join-page, already game is created._
  - When _I enter my name and click on **join** button._
  - Then _I should be added as player and I should be redirected to the wait page, until game starts._

- [x] Criteria 3
  - Given _I'm on join-page, already game is created._
  - When _I enter my name and click on **join** button._
  - Then _I should be joined with my name as player name._

**Comment by HarVar-B** [comment]
![screen shot 2018-02-16 at 11 36 38 am](https://user-images.githubusercontent.com/34670602/36295461-b9b4f046-130d-11e8-94c4-4c4ab84c8ff9.png)

Should not accept invalid names for players.
