### ISSUE TITLE
Some UI changes according to client feedback

### ISSUE THREAD

**Issue by HarVar-B** [STEP-tw/acquire-legends#46]
* [x] Maintain a single font style throughout the app.
* [x] Use Icons for representing hotels.
* [x] Change the way of displaying user sequence.
* [x] Align the game view. 
* [x] Display player name in proper manner.
* [x] Use proper color variation.

**Comment by sachin-poolamannil** [comment]
To display player name, better to _use an icon_ and display the player name next to that instead of showing **Logged in as player_x**.

**Comment by mrveera** [comment]
Hey this commit broken existing feature ( Activity log )
fix it ASAP
