### ISSUE TITLE
Decide the sequence of player turn

### ISSUE THREAD

**Issue by sachin-poolamannil** [STEP-tw/acquire-legends#5]
As a _player_

I want to _know the sequence of players._

So that I may _wait till my turn comes._

**Additional Details**

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I'm on game page._
  - When _host player starts the game._
  - Then _the sequence of players turn should be done._
- [x] Criteria 2
  - Given _I'm on game page._
  - When _sequencing is done._
  - Then _the players sequence should be displayed._

**Comment by mrveera** [comment]
As a part of this story, change order of displaying players on top
