### ISSUE TITLE
Player should get random tiles from tilebox

### ISSUE THREAD

**Issue by yogiraj99** [STEP-tw/acquire-legends#52]
As a _player_

I want to _get random tile_

So that I may _use it to make strategy_

**Additional Details**
Previously player was getting tiles sequentially.

**Acceptance Criteria**
- [x] Criteria 1
  - Given _I have already joined the game_
  - When _game starts_
  - Then _I should get 6 random tiles._

- [x] Criteria 2
  - Given _it is my turn_
  - When _my turn ends_
  - Then _I should get random tile._

**Comment by mrveera** [comment]
I am not clear with acceptance criteria
Change acceptance criteria according to game rules
