### ISSUE TITLE
Player should get chance to break tie in merging hotels

### ISSUE THREAD

**Issue by yogiraj99** [STEP-tw/acquire-legends#58]
As a _Player_

I want to _get chance to break tie in merger._

So that I may _get advantage of my choice_

**Additional Details**
I placed merger tile.

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I placed merger tile_
  - When _there is tie between two largest hotels_
  - Then _I should be asked for which hotel to survive._

- [x] Criteria 2
  - Given _I placed merger tile, merger is of more than 2 hotels_
  - When _there is tie between two smaller hotels_
  - Then _I should be asked for which hotel to merge fisrt._

**Comment by mrveera** [comment]
It broke existing feature (buy shares)
