### ISSUE TITLE
Determine whether game over condition is met.

### ISSUE THREAD

**Issue by yogiraj99** [STEP-tw/acquire-legends#60]
As a _player_

I want to _over the game_

So that I may _end the game._

**Additional Details**
Game is running.
**Acceptance Criteria**

- [x] Criteria 1
  - Given _I placed tile._
  - When _any hotel size is greater than 41_
  - Then _game should end_

- [x] Criteria 2
  - Given _I placed tile._
  - When _all running hotels are stable._
  - Then _game should end._

- [x] Criteria 3
  - Given _I placed tile._
  - When _there are no tiles left in game._
  - Then _game should end_

**Comment by mrveera** [comment]
If it is condition in code How can i test it

**Comment by mrveera** [comment]
you have to do commits for this issue to resolve

**Comment by yogiraj99** [comment]
#87  After merging if all hotels become stable it is still giving chance to next player.
