### ISSUE TITLE
Announce rank

### ISSUE THREAD

**Issue by yogiraj99** [STEP-tw/acquire-legends#61]
As a _player_

I want to _get rank after game is over_

So that I may _know my rank._

**Additional Details**

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _game over condition is satisfied_
  - When _game ends_
  - Then _I should get minority, majority bonus when applicable_

- [ ] Criteria 2
  - Given _game over condition is satisfied_
  - When _game ends_
  - Then _I should get money in exchange of all running hotel shares at cost of current share price._

- [ ] Criteria 3
  - Given _game ends_
  - When _I get majority, minority bonus and get in money exchange of shares_
  - Then _I should get rank._

**Comment by mrveera** [comment]
UI for winner have to improve 
Congo message for  winner should be added
