### ISSUE TITLE
Invalid tile of player should be replaced by valid tile

### ISSUE THREAD

**Issue by harshadt21** [STEP-tw/acquire-legends#66]
As a _player_

I want to _get valid tile, in place of invalid tile which i have _

So that I may _place valid tile._

**Additional Details**
*Game is running
*Two stable hotels are running
*Player has a tile which can merge two running stable hotels

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I have invalid tile_
  - When _I try to place it_
  - Then _invalid tile should be removed_
- [x] Criteria 2
  - Given _I have invalid tile_
  - When _I try to place it_
  - Then _I should get valid tile if available_

**Comment by mrveera** [comment]
As a player, I should be informed when I have invalid tiles, If you  replace internally, How will I know

**Comment by yogiraj99** [comment]
#89 Notification is not going unless you refresh the page.
