### ISSUE TITLE
Deployment of game on remote server

### ISSUE THREAD

**Issue by raipragyaa** [STEP-tw/acquire-legends#72]
As a _Admin_

I want to _deploy my game on Heroku_

So that _anyone can play the game using internet_

**Additional Details**

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _I have a working game_
  - When _I run the deployment script after having an account on Heroku_
  - Then _my game should be hosted on that_

**Comment by mrveera** [comment]
Maybe we deployed but not everyone aware of it. How it works
