### ISSUE TITLE
Player should be able to confirm before placing a tile.

### ISSUE THREAD

**Issue by aditilahare** [STEP-tw/acquire-legends#76]
As a _player_

I want to _confirm before placing a tile_

So that I may _avoid placing tile accidentally_

**Additional Details**
* I have already joined the game.
* Game is running.

**Acceptance Criteria**

- [x] Criteria 1
  - Given _Its my turn_
  - When _I choose a tile and click on confirm button _
  - Then _the tile should be placed on the board._
- [x] Criteria 2
  - Given _Its my turn_
  - When _I choose a tile and didn't click on confirm button_
  - Then _the tile shouldn't be placed on the board_

**Comment by yogiraj99** [comment]
#97

Sometimes in Safari it is not working
