### ISSUE TITLE
As a player, while disposing of shares I should be   informed what is state of merge and current action regarding to merge

### ISSUE THREAD

**Issue by mrveera** [STEP-tw/acquire-legends#79]

**Comment by mrveera** [comment]
I am not sure about its label. If you have any idea please let me know

**Comment by yogiraj99** [comment]
**Player should be informed who is disposing shares currently**

![screenshot 2018-03-05 22 15 59](https://user-images.githubusercontent.com/34642513/37138834-98c08052-22d1-11e8-8fb5-e10b6bbb01cc.png)
